# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

name: Release storage-libs libraries to Charmhub

on:
  push:
    branches:
      - main

jobs:
  ci-tests:
    uses: ./.github/workflows/ci.yaml

  release-to-charmhub:
    name: Release latest version of libs to Charmhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release bumped charm libraries to Charmhub
        uses: canonical/charming-actions/release-libraries@2.2.2
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"